WebApp_17_1_4/Controllers/UtilsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.Data;
using WebApp.Models;
using WebApp.Classes;
using System.IO;
using DevExtreme.AspNet.Mvc;
using Newtonsoft.Json;
using DevExtreme.AspNet.Data;

namespace WebApp.Controllers
{
    [Authorize]
    public class UtilsController : Controller
    {
        private readonly ILogger _logger;
        private readonly WebAppDbContext _context;

        public UtilsController(ILogger<UtilsController> logger, WebAppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult FunctionsDocumentation()
        {
            return View();
        }

        public ActionResult ShowFunctionPdf(string functionName)
        {
            FunctionDocumentation item = new FunctionDocumentation() { functionName = functionName };
            string fileNamePdf = item.getFileNamePdf;
            if (!item.existsPdf)
            {
                return NotFound(String.Format("Function Documentation '{0}' not found !!", item.functionName));
            }
            try
            {
                var fs = System.IO.File.ReadAllBytes(item.getFullFileNamePdf);
                //    //FileStream fs = new FileStream(filePathName, FileMode.Open, FileAccess.Read, FileShare.Read);
                //    return File(fs, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml");
                return new FileContentResult(fs, "application/pdf");
            }
            catch (Exception e)
            {
                string error = String.Format("{0} / {1}", e.Message, e.Source);
                _logger.LogError(String.Format("{0} -  {1}", "Utils.ShowFunctionPdf()", error));
                return BadRequest(error);
            }
        }

        [AllowAnonymous]
        public ActionResult DownloadDoc(string fileName)
        {
            string relativePath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "Download\\Docs");
            string fullFileName = System.IO.Path.Combine(relativePath, fileName);

            if (!System.IO.File.Exists(fullFileName))
            {
                return NotFound(String.Format("Document '{0}' not found !!", fileName));
            }
            try
            {
                var fs = System.IO.File.ReadAllBytes(fullFileName);
                return new FileContentResult(fs, "application/pdf");
            }
            catch (Exception e)
            {
                string error = String.Format("{0} / {1}", e.Message, e.Source);
                _logger.LogError(String.Format("{0} -  {1}", "DownloadDoc)", error));
                return BadRequest(error);
            }
        }



        [HttpGet]
        public ActionResult GetFunctionNames(DataSourceLoadOptions loadOptions)
        {
            List<FunctionDocumentation> items = new List<FunctionDocumentation>();
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_DailyExecution });
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_AssayUtilization });
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_UserRoles });
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_DataImport });
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_DataMining });
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_LogFiles }); 
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_UserManual });
            items.Add(new FunctionDocumentation() { functionName = Lookup.Function_Documentation_RnDExtractions });
            return Content(JsonConvert.SerializeObject(DataSourceLoader.Load(items.OrderBy(t=>t.functionName), loadOptions)), "application/json");
        }

        [HttpPost]
        public ActionResult UploadPdf(string functionName)
        {
            try
            {
                FunctionDocumentation item = new FunctionDocumentation() { functionName = functionName };
                if (item == null)
                {
                    Response.StatusCode = 500;
                }
                var myFile = Request.Form.Files["myFile"];
                var fullFileName = item.getFullFileNamePdf;
                if (!Directory.Exists(Path.GetDirectoryName(fullFileName)))
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(fullFileName));
                }
                using (var fileStream = System.IO.File.Create(fullFileName))
                {
                    myFile.CopyTo(fileStream);
                }
            }
            catch
            {
                Response.StatusCode = 400;
            }

            return new EmptyResult();
        }

        // POST: Utils/deleteFilePdf/5
        public JsonResult deleteFilePdf(string id)
        {
            string ret = "";
            FunctionDocumentation item = new FunctionDocumentation() { functionName = id };
            string fileNamePdf = item.getFileNamePdf;
            if (!item.existsPdf)
            {
                ret = String.Format("File '{0}' not found !!", fileNamePdf);
            } else
            {
                try
                {
                    System.IO.File.Delete(item.getFullFileNamePdf);
                }
                catch (Exception e)
                {
                    ret = String.Format("[deleteFilePdf] - {0} / {1}", e.Message, e.Source);
                }
            }
            return Json(ret);
        }

    }
}

WebApp_17_1_4/Views/Utils/FunctionsDocumentation.cshtml
<div class="long-title"><h3>Functions Documentation</h3></div>

<script type="text/javascript">

    function getFileUploaderInstance() {
        return $("#file-uploader").dxFileUploader("instance");
    }

    function getDataGridInstance() {
        return $("#grid-container").dxDataGrid("instance");
    }

    function goViewPdf(id) {
        $("#functionName").val(id);
        $("#list").attr("action", '@Url.Action("ShowFunctionPdf", "Utils")');
        $("#list").attr("target", "_blank");
        $("#list").submit();
        $("#list").attr("target", "");    // Ripristino Target
        return false;
    }

    function goUpload(id) {
        var uploader = getFileUploaderInstance();
        var url = uploader.option("uploadUrl");
        uploader.option("value", "");
        url = updateQueryStringParameter(url, "functionName", id);
        uploader.option("uploadUrl", url);
        $('#DivUpload').modal({
            keyboard: true
        }, 'show');
        return false;
    }

    function fileUploader_onUploaded(e) {
        $('#DivUpload').modal("hide");
        getDataGridInstance().refresh();
        DevExpress.ui.notify("File Loaded!", "info");
    }

    function goDeleteFile(id) {
        bootbox.confirm({
            message: "Do you wish to remove PDF file?", title: id, callback: function (result) {
                if (result) {
                    $.ajax({
                        url: '@Url.Action("deleteFilePdf")',
                        type: 'POST',
                        data: { id: id },
                        success: function (data) {
                            if (data != "") {
                                bootbox.alert(data);
                            } else {
                                getDataGridInstance().refresh();
                                DevExpress.ui.notify("File deleted!", "info");
                            }
                        }
                    });
                }
                return true;
            }
        });
    }


</script>

<br />

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "list" }))
{
    @Html.Hidden("functionName");
    <div class="row">
        <div class="col-md-6 col-md-push-3">
            <div style="margin-right: 10px;">
                @(Html.DevExtreme().DataGrid()
                .ID("grid-container")
                .DataSource(d => d.WebApi().Controller("Utils").LoadAction("GetFunctionNames").Key("functionName"))
                .HoverStateEnabled(true)
                .Columns(c =>
                {
                c.Add().DataField("functionName").Caption("Function").Width("50%");
                c.Add().DataField("existsPdf").Caption("Exists PDF").Width("30%").Alignment(HorizontalAlignment.Center)
                        .CellTemplate(@<div>
                                        <% if (data.existsPdf) { %>
                                        <span class="text-success">LOADED</span>
                                        <% } else { %>
                                        <span class="text-danger"><b>NOT LOADED</b></span>
                                        <% } %>
                                    </div>);
                c.Add()
                        .Alignment(HorizontalAlignment.Left)
                        .Width(120)
                        .DataField("functionName")
                        .AllowFiltering(false)
                        .AllowSorting(false)
                        .AllowEditing(false)
                        .AllowExporting(false)
                        .Caption("")
                        .CellTemplate(@<div>
                                <a href="#" onclick="goUpload('<%= value %>');" class="btn btn-primary btn-xs fa fa-upload" title="Load Function Documentation"></a>
                                <% if (data.existsPdf) { %>                
                                    <span>&nbsp;</span>
                                    <a href="#" onclick="goDeleteFile('<%= value %>');" class="btn btn-danger btn-xs fa fa-remove" title="Remove Function Documentation"></a>
                                    <span>&nbsp;</span>
                                    <a href="#" onclick="goViewPdf('<%= value %>');" class="btn btn-default btn-xs fa fa-info-circle" title="Show Function Documentation"></a>
                                <% } %>
                        </div>);
                    })
                )
            </div>
        </div>
    </div>
}
<br />

<div class="modal fade" id="DivUpload" tabindex="-1" role="dialog" aria-labelledby="Upload File" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="titolo_upload">Load Function Documentation</h4>
            </div>
            <div class="modal-body">
                <div id="fileuploader">
                    <div class="widget-container">
                        @(Html.DevExtreme().FileUploader()
                                        .ID("file-uploader")
                                        .Name("myFile")
                                        .Multiple(false)
                                        .Accept("application/pdf")
                                        .UploadMode(FileUploadMode.Instantly)
                                        .UploadUrl(Url.Action("UploadPdf", "Utils", new { functionName = "" }))
                                        .OnUploaded("fileUploader_onUploaded")
                                        .LabelText("Select a PDF file")
                                        .SelectButtonText("Select file")
                        )
                        <div class="content" id="selected-files"></div>
                    </div>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
</div>